// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwITd4L7-HuA3GaRpYDlvAt0Z67iyS1_E',
    appId: '1:529127507002:ios:553c4ab37385935f94a103',
    messagingSenderId: '529127507002',
    projectId: 'hastkala-39a7d',
    databaseURL: 'https://hastkala-39a7d-default-rtdb.firebaseio.com',
    storageBucket: 'hastkala-39a7d.firebasestorage.app',
    androidClientId: '529127507002-5asf5be60p3qvhpnlmcoas4kkm7bpphf.apps.googleusercontent.com',
    iosClientId: '529127507002-pv9v7ul7iuqfqki1h48vcmrja6m18ftl.apps.googleusercontent.com',
    iosBundleId: 'com.example.cartify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAI9EflFM6F-yCm2QAHBEaPyhdnqD4TanI',
    appId: '1:529127507002:web:de2d4201aac68c7394a103',
    messagingSenderId: '529127507002',
    projectId: 'hastkala-39a7d',
    authDomain: 'hastkala-39a7d.firebaseapp.com',
    databaseURL: 'https://hastkala-39a7d-default-rtdb.firebaseio.com',
    storageBucket: 'hastkala-39a7d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP4vYMizAAbEcTNPx0tMLPNPwO-qlK0yc',
    appId: '1:529127507002:android:2b3f507fe5da298694a103',
    messagingSenderId: '529127507002',
    projectId: 'hastkala-39a7d',
    databaseURL: 'https://hastkala-39a7d-default-rtdb.firebaseio.com',
    storageBucket: 'hastkala-39a7d.firebasestorage.app',
  );

}